services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.2
    container_name: elasticsearch932
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata932:/usr/share/elasticsearch/data
    networks:
      - elastic932

  kibana:
    image: docker.elastic.co/kibana/kibana:9.3.2
    container_name: kibana932
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch932:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic932

volumes:
  esdata932:

networks:
  elastic932:
    driver: bridge  
